# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      lexical-dependencies:
        patterns:
          - "lexical"
          - "@lexical/clipboard"
          - "@lexical/code"
          - "@lexical/file"
          - "@lexical/hashtag"
          - "@lexical/link"
          - "@lexical/list"
          - "@lexical/mark"
          - "@lexical/overflow"
          - "@lexical/plain-text"
          - "@lexical/react"
          - "@lexical/rich-text"
          - "@lexical/selection"
          - "@lexical/table"
          - "@lexical/utils"
      electron-forge-dependencies:
        patterns:
          - "@electron-forge/cli"
          - "@electron-forge/maker-deb"
          - "@electron-forge/maker-dmg"
          - "@electron-forge/maker-rpm"
          - "@electron-forge/maker-squirrel"
          - "@electron-forge/maker-zip"
          - "@electron-forge/plugin-auto-unpack-natives"
          - "@electron-forge/plugin-fuses"
          - "@electron-forge/plugin-vite"
        exclude-patterns:
          - "@electron/fuses"
      tailwind-dependencies:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "prettier-plugin-tailwindcss"
    reviewers:
      - RyotaAbe1014
